"""Turn the recorded metrics into LaTeX the manuscript inputs.

Writes two files beside the paper:

  macros.tex      one `\\newcommand` per recorded quantity, so the document contains no
                  hand-typed figure. Recompiling after a pipeline change updates every
                  number that changed and only those.
  provenance.tex  an appendix listing the code commits, library versions and input
                  manifest behind those numbers.

`spread.mean_bps_expiry` becomes `\\SpreadMeanBpsExpiry`. LaTeX command names cannot contain
digits, so digits are spelled out: `h.h12.p_value` becomes `\\HHOneTwoPValue`.

Formatting is decided here, once, from the unit recorded with each value - basis points to
two decimals, counts with thousands separators, fractions as percentages. The alternative is
a format specifier at each of several hundred call sites in the document, which is where
inconsistency creeps in.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any, Dict

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config.settings import RESULTS_DIR  # noqa: E402
from utils.logger import setup_logger  # noqa: E402
from utils.provenance import load_meta, load_metrics  # noqa: E402

logger = setup_logger("Macros", "stage7_report.log")

MACROS_PATH = Path(RESULTS_DIR) / "macros.tex"
PROVENANCE_PATH = Path(RESULTS_DIR) / "provenance.tex"

_DIGITS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
           "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def macro_name(key: str) -> str:
    """`spread.mean_bps_expiry` -> `SpreadMeanBpsExpiry`."""
    parts = []
    for chunk in re.split(r"[._\-]", key):
        if not chunk:
            continue
        word = "".join(_DIGITS.get(c, c) for c in chunk)
        parts.append(word[:1].upper() + word[1:])
    return "".join(parts)


def tex_escape(text: str) -> str:
    for old, new in (("\\", r"\textbackslash "), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                     ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                     ("~", r"\textasciitilde "), ("^", r"\textasciicircum ")):
        text = text.replace(old, new)
    return text


def _thousands(value: float, decimals: int = 0) -> str:
    return f"{value:,.{decimals}f}"


def format_value(value: Any, unit: str) -> str:
    """Render one value the way the manuscript should read it.

    Driven by the unit the recorder supplied. A fraction becomes a percentage because that
    is how the prose discusses it, and recording the fraction while displaying the
    percentage keeps the stored value in its natural units.
    """
    if isinstance(value, str):
        return tex_escape(value)
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return _thousands(value)

    number = float(value)
    if unit == "fraction":
        return f"{number * 100:.2f}"
    if unit == "per cent":
        return f"{number:.2f}"
    if unit in ("basis points", "ratio", "index", "seconds", "months"):
        return f"{number:.2f}"
    if unit == "rupees per share":
        # Kyle's lambda is order 1e-4; two decimals would print it as 0.00.
        return f"{number:.3g}"
    if unit in ("shares", "records", "snapshots", "pairs", "episodes"):
        return _thousands(number, 0)
    if unit in ("millions", "thousands"):
        return f"{number:,.2f}"
    if abs(number) >= 1000:
        return _thousands(number, 0)
    if abs(number) < 0.01 and number != 0:
        return f"{number:.3g}"
    return f"{number:.4f}".rstrip("0").rstrip(".")


def _p_value(number: float) -> str:
    """p-values read badly at fixed precision on either side of the range.

    Scientific notation below 1e-4, since four decimals renders every strong result as
    "0.0000" and a reader cannot tell 1e-5 from 1e-30. Wrapped in `\\ensuremath` because the
    result is math-mode content cited from ordinary table cells and running text, and a bare
    `\\times` outside maths is a fatal LaTeX error rather than a formatting wobble.
    """
    if number < 1e-4:
        mantissa, exponent = f"{number:.2e}".split("e")
        return rf"\ensuremath{{{mantissa}\times 10^{{{int(exponent)}}}}}"
    return f"{number:.4f}"


def build() -> int:
    metrics = load_metrics()
    if not metrics:
        logger.warning("[MACROS] no metrics recorded; run collect_metrics first")
        MACROS_PATH.parent.mkdir(parents=True, exist_ok=True)
        MACROS_PATH.write_text("% no metrics recorded\n", encoding="utf-8")
        return 1

    lines = [
        "% Generated by stage7_report/build_macros.py from data/results/metrics.json.",
        "% Do not edit: every value here is produced by the pipeline and overwritten on",
        "% the next run. To change a number, change the code that computes it.",
        "",
    ]
    seen: Dict[str, str] = {}
    for key in sorted(metrics):
        entry = metrics[key]
        name = macro_name(key)
        if name in seen:
            # Two keys colliding on one macro name would silently give the document
            # whichever was written last.
            logger.error(f"[MACROS] name collision: {key} and {seen[name]} both give \\{name}")
            continue
        seen[name] = key

        unit = entry.get("unit", "")
        value = entry.get("value")
        rendered = (_p_value(float(value))
                    if key.endswith("p_value") and isinstance(value, (int, float))
                    else format_value(value, unit))
        lines.append(rf"\newcommand{{\{name}}}{{{rendered}}}")

    MACROS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info(f"[MACROS] {len(seen)} macros -> {MACROS_PATH}")

    _build_provenance(metrics)
    return 0


def _build_provenance(metrics: Dict[str, Any]) -> None:
    """The appendix a referee asking 'where does this number come from' is handed."""
    meta = load_meta()
    code = meta.get("code", {})
    libraries = meta.get("libraries", {})
    inputs = meta.get("inputs", {})

    rows = [
        r"\section*{Appendix: provenance}",
        r"Every figure in this document is generated. The values are recorded by the code "
        r"that computes them, written to \texttt{data/results/metrics.json}, and reach this "
        r"document only as macros; no number is typed in by hand. The tables below record "
        r"the state of the code, the environment and the input data at the time of "
        r"generation.",
        "",
        r"\subsection*{Code}",
        r"\begin{tabular}{lll}",
        r"\toprule",
        r"Repository & Commit & Working tree \\",
        r"\midrule",
    ]
    for name, state in code.items():
        if not state.get("available"):
            rows.append(rf"{tex_escape(name)} & not a git checkout & --- \\")
            continue
        commit = (state.get("commit") or "unknown")[:12]
        dirty = "modified" if state.get("dirty") else "clean"
        rows.append(rf"{tex_escape(name)} & \texttt{{{commit}}} & {dirty} \\")
    rows += [r"\bottomrule", r"\end{tabular}", "", r"\subsection*{Environment}",
             r"\begin{tabular}{ll}", r"\toprule", r"Package & Version \\", r"\midrule"]
    for name, version in libraries.items():
        rows.append(rf"{tex_escape(name)} & {tex_escape(str(version))} \\")
    rows += [r"\bottomrule", r"\end{tabular}", "", r"\subsection*{Input data}"]
    rows.append(
        rf"{inputs.get('file_count', 0)} raw files, "
        rf"{inputs.get('total_bytes', 0) / 1e9:,.1f} GB. Files are identified by name, byte "
        rf"count and modification time rather than by content hash: at this scale hashing "
        rf"costs more than the analysis, and size with timestamp already distinguishes a "
        rf"different vintage of the same session. The full manifest is recorded in "
        rf"\texttt{{metrics.json}}."
    )
    rows += ["", r"\subsection*{Recorded quantities}",
             rf"{len(metrics)} quantities are recorded, each with its unit, the module that "
             rf"produced it and a note describing the computation."]

    PROVENANCE_PATH.write_text("\n".join(rows) + "\n", encoding="utf-8")
    logger.info(f"[MACROS] provenance appendix -> {PROVENANCE_PATH}")


if __name__ == "__main__":
    raise SystemExit(build())
